SELECT * FROM customer where discount_applied='Yes';


--total revenue generated by male and female
Select gender ,Sum(purchase_amount) from customer
group by gender

--customer used a discount but still spend more than average
Select customer_id, purchase_amount from customer 
where discount_applied ='Yes' and purchase_amount >= (select avg(purchase_amount) from customer) 

--avg purchase amount by each customer
Select customer_id, avg(purchase_amount) from customer
group by customer_id

--top 5 product with highest average reviewe rating
select item_purchased, round(avg(review_rating::numeric),2) from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare the avg purchase amounts between standard and express shipping
Select shipping_type,round(avg(purchase_amount),2) from customer
where shipping_type in('Standard','Express')
group by shipping_type

--compare avg spend and revenue between subscribers and Non subscribers
select  subscription_status,
count(customer_id),
round(avg(purchase_amount),2) as avg_spent ,
round(sum(purchase_amount),2) as revenue
from customer
group by subscription_status
order by revenue,avg_spent desc

--top 5 products have highest % of purchases with discount applied
select item_purchased,
round(sum(100*case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


--segmentation of customer into new,loyal,returning based on their previous purchase count
with cte as(
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal' 
	end as customer_segment from customer
)
select customer_segment,count(*)
from cte
group by customer_segment


--top 3 most purchase product with in each category
with cte as(
select item_purchased,category,
count(customer_id) as total_numbers,
row_number() over (partition by category order by count(customer_id)desc) as item_rnk
from customer
group by  category,item_purchased
)

select item_rnk,category,item_purchased,total_numbers 
from cte where item_rnk<=3;

--customers who are repeat buyers  are also like to subscribe
select subscription_status,count(customer_id) as rpt_customers
from customer
where previous_purchases>5
group by subscription_status

--revenue contribution of each age group
select age_group, sum(purchase_amount) from customer
group by age_group
order by sum(purchase_amount) DESC
